#!/bin/env bash
# A script that execute a program silently without showing stdout or stderr on terminal.

if [ ! $1 ]; then
	echo "$0 [progran] [arguments]"
	exit 1
fi

if [[ $(id -u) == 0 ]]; then
  echo "warning: program was executed under root priviledge"
fi

if [ ! $2 ]; then 
  nohup $1 &> /dev/null &
else
  nohup $1 ${@:2} &> /dev/null &
fi
